name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'
        bundler-cache: true
    - name: Run SwiftLint
      uses: maierj/fastlane-action@v3.0.0
      with: 
        lane: 'lint'
        subdirectory: 'fastlane'

  test:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'
    - uses: AckeeCZ/load-xcode-version@1.0
    - name: Run UI Tests
      uses: maierj/fastlane-action@v3.0.0
      with: 
        lane: 'test'
        subdirectory: 'fastlane'

  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'
    - uses: AckeeCZ/load-xcode-version@1.0
    - name: Build
      uses: maierj/fastlane-action@v3.0.0
      with: 
        lane: 'build'
        subdirectory: 'fastlane'
